name: brasilcard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.5.0
  get_it: ^8.0.3
  http: ^1.3.0
  hive: ^2.2.3
  flutter_screenutil: ^5.9.3
  hive_generator: ^2.0.1
  equatable: ^2.0.7
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  flutter_mobx: ^2.3.0
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
